### ISSUE TITLE
service 层的操作

### ISSUE THREAD

**Issue by spland** [sunweiguo/MMall#3]
你好，在对数据库层面做增删改操作的时候你不加事务的吗？（表示疑惑）

**Comment by sunweiguo** [comment]
> 你好，在对数据库层面做增删改操作的时候你不加事务的吗？（表示疑惑）

事务控制还是需要的。。。这个项目是后来重构，没有太注意逻辑层面，主要是如何改为spring cloud

**Comment by spland** [comment]
ok
